In [1]:
import os
import math

import numpy as np
import matplotlib.pyplot as plt

In [2]:
## Problem 3

In [3]:
### Problem 3.1

# Prior class probabilities with Laplace Smoothing
logye, logyj, logys = np.log((10 + 1/2)/(30 + 3/2)), np.log((10 + 1/2)/(30 + 3/2)), np.log((10 + 1/2)/(30 + 3/2))

np.exp(logye), np.exp(logyj), np.exp(logys)

(0.3333333333333333, 0.3333333333333333, 0.3333333333333333)

In [4]:
# Compute the count for each letter in the document given by file with name fname
def get_counts(fname):
    x = np.zeros(27, dtype=int)
    
    with open(fname) as f:
        for line in f:
            for ch in line.strip():
                if ch == ' ':
                    x[26] += 1
                else:
                    x[ord(ch)-ord('a')] += 1
                    
    return x

In [5]:
# Assume 0-9 -> english, 10-19 -> japanese, 20 -> 29 -> spanish
# Example: 15 -> j5.txt
def get_filename(idx):
    pfx = ['e', 'j', 's']
    return f'../languageID/{pfx[idx//10]}{idx%10}.txt'

In [6]:
# Y -> {e: 0, j: 1, s: 2}
# X -> character count for each document
def get_train_data():
    Y = np.array([i//10 for i in np.arange(30)])
    X = np.array([get_counts(get_filename(idx)) for idx in np.arange(30)])
    
    return X, Y

In [9]:
X, Y = get_train_data()

In [10]:
### Problem 3.2

# idx determines the lang {e: 0, j: 1, s: 2}
def calc_params(idx):
    # Accumulate counts for language idx
    p = X[idx*10:(idx+1)*10].sum(axis=0)

    # Laplace Smoothing (and broadcasting)
    p = p + 1/2

    # Normalize
    return p / p.sum()

In [12]:
pe, pj, ps = calc_params(0), calc_params(1), calc_params(2)

# Conditional prob of each char given class label
pe, pj, ps

(array([0.06024017, 0.01114824, 0.02153561, 0.02199874, 0.10549472,
        0.01895531, 0.01749975, 0.04727249, 0.05547653, 0.00142248,
        0.00373813, 0.02901188, 0.02054319, 0.05799067, 0.06454067,
        0.01677197, 0.00056237, 0.05388865, 0.06626088, 0.08022098,
        0.02669622, 0.00929571, 0.0155149 , 0.00115783, 0.01386086,
        0.00062854, 0.17827252]),
 array([1.34175414e-01, 1.10656467e-02, 5.58619463e-03, 1.75413627e-02,
        6.13058175e-02, 3.94947518e-03, 1.42679239e-02, 3.23429995e-02,
        9.88080413e-02, 2.38391745e-03, 5.84593489e-02, 1.45881516e-03,
        4.05265967e-02, 5.77477317e-02, 9.28304572e-02, 8.89521437e-04,
        1.06742572e-04, 4.35865504e-02, 4.29460950e-02, 5.80323786e-02,
        7.19089130e-02, 2.49066002e-04, 2.01031845e-02, 3.55808575e-05,
        1.44102473e-02, 7.86336951e-03, 1.07418609e-01]),
 array([1.04831978e-01, 8.25424305e-03, 3.76232726e-02, 3.98491359e-02,
        1.14106409e-01, 8.62522027e-03, 7.20314094e-03, 4.544470

In [25]:
# Latex output

def latex_table(pl):
    headers = ['character', '$p(c \mid e)$']

    textabular = '|| c | c ||'
    texheader = " & ".join(headers) + "\\\\"
    texdata = "\\hline\\hline\n"
    for i, p in enumerate(p):
        if i == 26:
            c = 'SPACE'
        else:
            c = chr(ord('a') + i)
        texdata += f'{c} & {p:.3f}\\\\\n'
        texdata += "\\hline\n"

    print("\\begin{tabular}{"+textabular+"}")
    print("\\hline")
    print(texheader)
    print(texdata,end="")
    print("\\end{tabular}")

In [30]:
### Problem 3.3

latex_table(ps)

\begin{tabular}{|| c | c ||}
\hline
character & $p(c \mid e)$\\
\hline\hline
a & 0.105\\
\hline
b & 0.008\\
\hline
c & 0.038\\
\hline
d & 0.040\\
\hline
e & 0.114\\
\hline
f & 0.009\\
\hline
g & 0.007\\
\hline
h & 0.005\\
\hline
i & 0.050\\
\hline
j & 0.007\\
\hline
k & 0.000\\
\hline
l & 0.053\\
\hline
m & 0.026\\
\hline
n & 0.054\\
\hline
o & 0.073\\
\hline
p & 0.024\\
\hline
q & 0.008\\
\hline
r & 0.059\\
\hline
s & 0.066\\
\hline
t & 0.036\\
\hline
u & 0.034\\
\hline
v & 0.006\\
\hline
w & 0.000\\
\hline
x & 0.003\\
\hline
y & 0.008\\
\hline
z & 0.003\\
\hline
SPACE & 0.166\\
\hline
\end{tabular}


In [33]:
### Problem 3.4

xtest = get_counts(f'../languageID/e10.txt')

xtest

array([164,  32,  53,  57, 311,  55,  51, 140, 140,   3,   6,  85,  64,
       139, 182,  53,   3, 141, 186, 225,  65,  31,  47,   4,  38,   2,
       492])

In [35]:
# Latex output

headers = ['character', 'count']

textabular = '|| c | c ||'
texheader = " & ".join(headers) + "\\\\"
texdata = "\\hline\\hline\n"
for i, p in enumerate(xtest):
    if i == 26:
        c = 'SPACE'
    else:
        c = chr(ord('a') + i)
    texdata += f'{c} & {p:}\\\\\n'
    texdata += "\\hline\n"

print("\\begin{tabular}{"+textabular+"}")
print("\\hline")
print(texheader)
print(texdata,end="")
print("\\end{tabular}")

\begin{tabular}{|| c | c ||}
\hline
character & count\\
\hline\hline
a & 164\\
\hline
b & 32\\
\hline
c & 53\\
\hline
d & 57\\
\hline
e & 311\\
\hline
f & 55\\
\hline
g & 51\\
\hline
h & 140\\
\hline
i & 140\\
\hline
j & 3\\
\hline
k & 6\\
\hline
l & 85\\
\hline
m & 64\\
\hline
n & 139\\
\hline
o & 182\\
\hline
p & 53\\
\hline
q & 3\\
\hline
r & 141\\
\hline
s & 186\\
\hline
t & 225\\
\hline
u & 65\\
\hline
v & 31\\
\hline
w & 47\\
\hline
x & 4\\
\hline
y & 38\\
\hline
z & 2\\
\hline
SPACE & 492\\
\hline
\end{tabular}


In [37]:
### Problem 3.5

xtest.T @ np.log(pe), xtest.T @ np.log(pj), xtest.T @ np.log(ps)

(-7831.531702560013, -8786.051104707092, -8457.039705604957)

In [42]:
### Problem 3.7

cm = np.zeros((3, 3), dtype=int)
labels = ['e', 'j', 's']

for label in range(3):
    for idx in range(10):
        fname = f'../languageID/{labels[label]}{idx}.txt'
        xtest = get_counts(fname)
        likelihood = np.array([xtest.T @ np.log(pe) + logye, xtest.T @ np.log(pj) + logyj, xtest.T @ np.log(ps) + logys])
        pred = np.argmax(likelihood)
        cm[pred, label] += 1
        
cm

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 10]])

In [ ]:
## Problem 4

import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# X -> flatten -> h1 -> out -> softmax -> cross entropy loss

d = 28 * 28 # Input Layer
d1 = 512    # Hidden Layer
k = 10      # Output Layer

In [ ]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)

In [ ]:
# Testing

torch.manual_seed(42)
N = 64
X = torch.rand(N, 28, 28)
Y = torch.randint(0, k, (N,))
w1 = torch.empty((d1, d)) # Hidden layer
b1 = torch.empty(d1)
nn.init.kaiming_uniform_(w1, a=math.sqrt(5))
bound = 1 / math.sqrt(d)
nn.init.uniform_(b1, -bound, bound)
w2 = torch.empty((k, d1)) # Output layer
b2 = torch.empty(k)
nn.init.kaiming_uniform_(w2, a=math.sqrt(5))
bound = 1 / math.sqrt(d1)
nn.init.uniform_(b2, -bound, bound)

w1.shape, b1.shape, w2.shape, b2.shape

In [ ]:
# Forward pass

# Flatten the input
# flat.shape = (N, d)
flat = X.view(N, -1)

# First hidden layer
lin1 = flat @ w1.T + b1
h1 = torch.maximum(lin1, torch.tensor(0)) # ReLU. Let broadcast do its work

# Output layer
out = h1 @ w2.T + b2

# Softmax
maxb, _ = torch.max(out, axis=1, keepdim=True)
out = out - maxb # Keep the values non-positive to avoid blowing up the exponents
p = torch.exp(out)
p = p / p.sum(axis=1, keepdim=True) # Softmax

# Cross entropy loss
loss = -torch.mean(torch.log(torch.gather(p, 1, Y.unsqueeze(dim=1)))).item()


h1.shape, out.shape, p.shape, loss, flat.shape

In [ ]:
# Backward Pass

# cross_entropy grad
dout = p - F.one_hot(Y)

# Output Layer grad
dw2 = torch.sum(dout.unsqueeze(dim=2) @ h1.unsqueeze(dim=1), axis=0)
db2 = dout.sum(axis=0)
dh1 = dout @ w2

# Hidden Layer grad
dlin1 = torch.zeros_like(dh1)
mask = lin1 >= 0
dlin1[mask] = dh1[mask]
dw1 = torch.sum(dlin1.unsqueeze(dim=2) @ flat.unsqueeze(dim=1), axis=0)
db1 = dlin1.sum(axis=0)

dout.shape, dw2.shape, db2.shape, dh1.shape, dw1.shape, db1.shape

In [ ]:
# Update

lr = 0.001

w2 = w2 - lr * dw2
b2 = b2 - lr * db2
w1 = w1 - lr * dw1
b1 = b1 - lr * db1

In [ ]:
## Forward pass testing

torch.manual_seed(42)
net = nn.Sequential(
    nn.Flatten(),
    nn.Linear(28 * 28, 512),
    nn.ReLU(),
    nn.Linear(512, 10),
)
outn = net(X)
tloss = F.cross_entropy(outn, Y)

tloss

In [ ]:
# Forward pass

class MLP:
    def __init__(self):
        d = 28 * 28
        d1 = 512
        k = 10
        
        # Hidden Layer
        self.w1 = torch.empty((d1, d))
        self.b1 = torch.empty(d1)
        nn.init.kaiming_uniform_(self.w1, a=math.sqrt(5))
        bound = 1 / math.sqrt(d)
        nn.init.uniform_(self.b1, -bound, bound)
        
        # Output Layer
        self.w2 = torch.empty((k, d1))
        self.b2 = torch.empty(k)
        nn.init.kaiming_uniform_(self.w2, a=math.sqrt(5))
        bound = 1 / math.sqrt(d1)
        nn.init.uniform_(self.b2, -bound, bound)
        
    def backprop(self, X, Y):
        ## Forward Pass
        
        # Hidden Layer
        lin1 = flat @ self.w1.T + self.b1
        h1 = torch.maximum(lin1, torch.tensor(0)) # ReLU. Let broadcast do its work
        
        # Output Layer
        logits = h1 @ self.w2.T + self.b2
        
        # Softmax
        maxb, _ = torch.max(logits, axis=1, keepdim=True)
        logits = logits - maxb # Keep the values non-positive to avoid blowing up the exponents
        p = torch.exp(logits)
        p = p / p.sum(axis=1, keepdim=True) # Softmax
        
        # Cross Entropy
        loss = -torch.mean(torch.log(torch.gather(p, 1, Y.unsqueeze(dim=1)))).item()
        
        ## Backward Pass
        # cross_entropy grad
        dout = p - F.one_hot(Y)

        # Output Layer grad
        dw2 = torch.sum(dout.unsqueeze(dim=2) @ h1.unsqueeze(dim=1), axis=0)
        db2 = dout.sum(axis=0)
        dh1 = dout @ self.w2

        # Hidden Layer grad
        dlin1 = torch.zeros_like(dh1)
        mask = lin1 >= 0
        dlin1[mask] = dh1[mask]
        dw1 = torch.sum(dlin1.unsqueeze(dim=2) @ flat.unsqueeze(dim=1), axis=0)
        db1 = dlin1.sum(axis=0)
        
        # Update
        self.w2 = self.w2 - lr * dw2
        self.b2 = self.b2 - lr * db2
        self.w1 = self.w1 - lr * dw1
        self.b1 = self.b1 - lr * db1
        
        return loss
        
    
mlp = MLP()

In [ ]:
## More Testing

torch.manual_seed(42)
N = 64
X = torch.rand(N, 28, 28)
Y = torch.randint(0, k, (N,))
lr = 0.001

for _ in range(100):
    loss = mlp.backprop(X, Y)
    print(loss)

In [ ]:
x = np.array([[2, 1, 0], [1, 1, 1], [0, 1, 0]])
p = np.array([0, 1, 0])
y = np.array([0, 5, 2])

for _ in range(1):
    p = p - 0.02 * 2/3 * x.T @ (x @ p - y)

p

In [ ]:
a = [23, 54, -12, 912, 6, 7, 12]
mn = np.mean(a)
var = np.sum(np.square(a - mn)) / (len(a) - 1)
std = np.sqrt(var)

std, (a - mn) / 339.6